# Generated by Django 3.1 on 2020-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200815_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'отдел', 'verbose_name_plural': 'отделы'},
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.CharField(default='wer', max_length=255),
        ),
    ]
