# Generated by Django 3.1 on 2020-08-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200818_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='number',
        ),
    ]
