# Generated by Django 3.1 on 2020-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_department_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
