# Generated by Django 3.1 on 2020-09-04 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employee_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_in_a_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='За кого голос'),
        ),
    ]
