# Generated by Django 3.1 on 2020-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200917_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='not_available.jpg', upload_to='user_photo', verbose_name='Фото'),
        ),
    ]
