# Generated by Django 3.1 on 2020-09-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200927_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employment_in_a_company',
            new_name='is_employment',
        ),
    ]
