# Generated by Django 3.1 on 2020-09-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200927_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_employment',
            new_name='employment',
        ),
    ]
