# Generated by Django 3.1 on 2020-09-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200927_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='voted',
        ),
    ]
